name: Playwright E2E tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  cypress-run:
    if: github.repository == 'redwoodjs/redwood'
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        node-version: ['14']
      fail-fast: true
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} | Node ${{ matrix.node-version }} latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache framework "node_modules"
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: node_modules_${{ runner.os }}_${{ hashFiles('**/yarn.lock') }}

      - name: Install framework modules
        run: yarn install --frozen-lockfile

      - name: Create a temporary directory
        id: createpath
        run: |
          project_path=$(node tasks/test-project/scripts/createTempDir)
          echo "::set-output name=project_path::$project_path"

      - name: Cache project "node_modules"
        uses: actions/cache@v2
        with:
          path: ${{ steps.createpath.outputs.project_path }}/**/node_modules
          key: project_modules_${{ runner.os }}_${{ hashFiles('packages/create-redwood-app/template') }}

      - name: Cache playwright deps "node_modules"
        uses: actions/cache@v2
        with:
           path: './playwright-cache'
           key: playwright_cache_${{ hashFiles('./playwright-cache')}}

      - name: Create a test project
        run:  yarn build:test-project ${{ steps.createpath.outputs.project_path }} --verbose --link --force

      - name: Install Playwright deps
        run:  npx --cache ./playwright-cache playwright install-deps chromium

      - name: Run tests
        run:  cd tasks/test-project/playwright && npx --cache ./playwright-cache playwright test
        env:
          PROJECT_PATH: ${{ steps.createpath.outputs.project_path }}
